[package]
name = "esbio"
version = "0.1.0"
authors = ["dlcgold <dlcgold96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
